@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12

start
:User executes FilterCommand;
:Retrieve the specified tag from user input;
if () then ([Valid tag])
    :Update filtered list with entries with matching tag;
    :Display success message;
else ([Invalid tag])
    :Display error message for invalid command format;
endif
stop

@enduml
