@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12

start
:User executes filter command;
:Retrieve tag from user input;
if () then ([Valid tag])
    :Update filtered list to contain entries with matching tag;
    :Display success message;
    :Display contact details;
else ([else])
    :Display error message for invalid command format;
endif
stop

@enduml
