@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12

start
:User executes ReminderCommand;
:Retrieve the number of days from user input;
if () then ([Valid Number of Days])
    :Update filtered list with upcoming interviews;
    :Display success message;
else ([Invalid Number of Days])
    :Display error message for invalid command format;
endif
stop

@enduml
